[package]
name = "regex_perf_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
regex-automata = "0.2.0"

[profile.release]
debug = true
opt-level = 3
